### ISSUE TITLE
Feature request: Microsoft monthly patch review 

### ISSUE THREAD

**Issue by askvpb** [xaitax/SploitScan#11]
I would like to findout if you help automating the process of checking all the monthly patches from Microsoft on Patch Tuesday and passing each CVE ID through a script, I use the script https://github.com/Immersive-Labs-Sec/msrc-api/blob/main/patch_review.py, is it possible to take the each of the cve ID and pass it through your script to output?

**Comment by xaitax** [comment]
Hi @askvpb 

the problem currently is that all databases have an API rate limit. But let me think of a solution.

I also use a script that is slightly more advanced (in my opinion for tracking those:
https://github.com/xaitax/PatchaPalooza

Cheers,
Alex
